//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBiblioteca
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Libro
    {
        [ScaffoldColumn(false)]
        public int idlibro { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El título es requerido"), MaxLength(55)]
        [Display(Name = "Título Libro")]
        public string titulo { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El autor es requerido"), MaxLength(75)]
        [Display(Name = "Autor(es)")]
        public string autor { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El ISBN es requerido"), MaxLength(5)]
        [Display(Name = "ISBN")]
        public string ISBN { get; set; }

        [Display(Name = "Fecha Publicación")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fecha_publ { get; set; }
        [DataType(DataType.Duration)]
        [Required(ErrorMessage = "Número de ejemplares requerido")]
        [Display(Name = "Número de Ejemplares")]
        public Nullable<int> numero { get; set; }

        [Required(ErrorMessage = "La categoría es requerida")]
        [Display(Name = "Categoría")]
        public Nullable<int> idcategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
